---
- hosts: localhost
  remote_user: zenika
  tasks:
    - name: install list of packages
      apt:
        name: "{{ packages_to_install }}"
        update_cache: yes
      vars:
        packages_to_install:
        - git
        - curl
        - openssh-server
        - openjdk-8-jdk
        - openjdk-8-doc
        - openjdk-11-jdk
        - openjdk-11-doc
        - maven
        - chromium-browser
      become: yes
    - name: set jdk 8 as default
      alternatives:
        name: java
        path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

    - name: get stats on nvm
      stat: path="{{ ansible_env.HOME }}/.nvm"
      register: nvm_stat

    - name: download nvm script
      get_url:
        dest: "{{ nvm_working_path }}"
        url: https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh
      when: not nvm_stat.stat.exists

    - name: run nvm script
      command: "bash {{ nvm_working_path }}/install.sh"
      become: true
      when: not nvm_stat.stat.exists

    - name: install latest Node LTS
      shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
      args:
        executable: /bin/bash
        creates: "{{ ansible_env.HOME }}/.nvm/alias/default"

    - name: Installation des package pré-requis à Docker
      become: yes
      apt: name={{ item }} update_cache=yes state=present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Ajout de la clé GPG officielle de Docker
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Ajout du repo apt Docker
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable

    - name: Installation de Docker
      become: yes
      apt: name=docker-ce update_cache=yes

    - name: Installation de pip
      become: yes
      apt: name=python-pip

    - name: Suppression de docker-py
      become: yes
      pip:
        name: docker-py
        state: absent

    - name: Installation du module pip docker-compose
      become: yes
      pip:
        name: docker-compose

    - name: install VS Code
      snap:
        name:
          - code
        classic: yes
      become: yes

    - name: install Intellij IDEA Community
      snap:
        name:
          - intellij-idea-community
        classic: yes
      become: yes

    - name: install Eclipse
      snap:
        name:
          - eclipse
        classic: yes
      become: yes