---
- hosts: pc-formation
  remote_user: zenika
  become: yes
  tasks:
    - name: install list of packages
      apt:
        name: "{{ packages_to_install }}"
        update_cache: yes
      vars:
        packages_to_install:
        - git
        - curl
        - openssh-server
        - openjdk-11-jdk
        - openjdk-11-doc
        - maven
        - chromium-browser