- name: get stats on nvm
  stat: path="{{ ansible_env.HOME }}/.nvm"
  register: nvm_stat

- name: download nvm script
  get_url:
    dest: "{{ nvm_working_path }}"
    url: https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh
  when: not nvm_stat.stat.exists

- name: run nvm script
  command: "bash {{ nvm_working_path }}/install.sh"
  become: true
  when: not nvm_stat.stat.exists

- name: install latest Node LTS
  shell: "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts"
  args:
    executable: /bin/bash
    creates: "{{ ansible_env.HOME }}/.nvm/alias/default"