- name: install VS Code
  snap:
    name:
      - code
    classic: yes
  become: yes

- name: install Intellij IDEA Community
  snap:
    name:
      - intellij-idea-community
    classic: yes
  become: yes

- name: install Eclipse
  snap:
    name:
      - eclipse
    classic: yes
  become: yes